image: node:24

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - npm ci
    - npm test
    - npm run build
    - npm --verbose publish
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always
